# version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: Admin123!*
    networks:
      - app_network
  api:
    image: "transaction:0.0.1"
    restart: always
    env_file:
      - ./file.env
    ports:
      - "8080:8080"
    command: "./api"
    networks:
      - app_network
  minio:
    image: minio/minio:RELEASE.2023-09-23T03-47-50Z
    container_name: minio
    user: "0:0"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
networks:
  app_network:
    driver: bridge
volumes:
  minio_storage: