CREATE TABLE IF NOT EXISTS limits (
    id BIGSERIAL PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    tenor INT,
    amount BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);