CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    uid VARCHAR(75) NOT NULL UNIQUE,
    email VARCHAR(150) NULL UNIQUE,
    google_id varchar(150) NULL UNIQUE,
    name VARCHAR(75) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);